sudo: false
dist: trusty

language: ruby
rvm:
  - 2.4.3

# TODO: Use MySQL on Travis CI
before_install:
  - sudo service mysql stop

install:
  - docker-compose -f .travis/docker-compose.yml build
  - docker-compose -f .travis/docker-compose.yml up -d

script:
  - docker-compose -f .travis/docker-compose.yml run --rm spring bin/rails db:create db:migrate
  - docker-compose -f .travis/docker-compose.yml exec spring rspec --format progress

branches:
  only:
    - master

notifications:
  email: false
