sudo: false
dist: trusty

language: ruby
rvm:
  - 2.4.3
bundler_args: --jobs=4 --without production development --path vendor/bundle

# TODO: Use MySQL on Travis CI
before_install:
  - sudo service mysql stop
  - docker-compose -f .travis/docker-compose.yml build travis_rspec
  - docker-compose -f .travis/docker-compose.yml run --rm travis_rspec
    bin/rails db:create db:migrate

script:
  - docker-compose -f .travis/docker-compose.yml run --rm travis_rspec
    bundle exec rspec --format progress


branches:
  only:
    - master

notification:
  email: false
