sudo: false
dist: trusty

language: ruby
rvm:
  - 2.4.3

# TODO: Use MySQL on Travis CI
before_install:
  - sudo service mysql stop

install:
  - docker-compose -f .travis/docker-compose.yml run --rm node yarn install

before_script:
  - docker-compose -f .travis/docker-compose.yml run --rm node /bin/sh -c "yarn lint && yarn build"
  - docker-compose -f .travis/docker-compose.yml build spring
  - docker-compose -f .travis/docker-compose.yml run --rm spring bin/rails db:create db:migrate

script:
  - docker-compose -f .travis/docker-compose.yml run --rm spring rspec --format progress

branches:
  only:
    - master

notifications:
  email: false
