version: '3'
volumes:
  app_data:
  db_data:
  node_modules:
services:
  app: &app_base
    container_name: app
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile.dev
    command: bundle exec rails s -b 0.0.0.0 --pid tmp/pids/server.pid
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app:cached
      - app_data:/app/vendor/bundle:cached
    tty: true
    stdin_open: true

  spring:
    <<: *app_base
    container_name: spring
    command: bundle exec spring server
    depends_on:
      - db
      - chrome
    ports: []

  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile.dev
    command: yarn watch
    ports:
      - 4000:4000
    volumes:
      - ./frontend/:/app/frontend:cached
      - ./frontend/node_modules:/app/frontend/node_modules:cached
      - ./public/assets/:/app/public/assets:cached

  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 5900:5900

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql:cached
