version: '3'
services:
  spring:
    build:
      context: ../
      dockerfile: ./docker/rails/Dockerfile.test
    command: bundle exec spring server
    environment:
      DATABASE_HOST: mysql
      DATABASE_USERNAME: root
    ports: []
    depends_on:
      - mysql
      - chrome
      - node

  chrome:
    image: selenium/standalone-chrome
    ports:
      - 5900:5900

  node:
    build:
      context: ../
      dockerfile: ./docker/node/Dockerfile.dev
    volumes:
      - ../frontend/:/app/frontend/
      - ../public/assets/:/app/public/assets

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
