version: '3'
services:
  spring:
    build:
      context: ../
      dockerfile: docker/rails/Dockerfile.test
    command: bundle exec spring server
    environment:
      DATABASE_HOST: mysql
      DATABASE_USERNAME: root
    ports: []
    depends_on:
      - mysql
      - chrome

  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 5900:5900

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
